### ISSUE TITLE
Unable to install plugin using Lazy plugin manager

### ISSUE THREAD

**Issue by ashish10alex** [magal1337/dataform.nvim#7]
Hi, 
Similar to yourself, being an avid neovim user I could not help myself by but write a plugin to interact with Dataform using Neovim. However my plugin uses a custom cli, I think you use `bq` cli which is much cleaner in terms of managing dependencies. The primary difference in my plugin is inline diagnostics.  I have not yet publicly made it available as I need to clean up my cli implementation. 

I was trying to get your plugin to work with Lazy nvim plugin manager however, I get this error. I wonder if it is something I am missing or a compatibility issue 

![CleanShot 2024-05-17 at 13 43 29@2x](https://github.com/magal1337/dataform.nvim/assets/34306898/9fa91fd3-8575-41f9-bc00-28bb882d9b84)

**Comment by magal1337** [comment]
Hey @ashish10alex  good catch! I actually copied this lazy installation part from other plugin that I have and didnt review it. Can you try to install it without the config variable? If not work I will try to replicate the bug and let you know.

**Comment by ashish10alex** [comment]
Hi, thanks without the config variable I start getting error like these when I try to use the plugin commands when I have a `.sqlx` file open. 

![CleanShot 2024-05-17 at 14 16 26@2x](https://github.com/magal1337/dataform.nvim/assets/34306898/d6ddffea-7b02-41ab-90dc-25f17f35a2ba)

**Comment by magal1337** [comment]
Hmm that's interesting. Which version of dataform/dataform-cli are you using right now? Also what happens if you try to save file first and then run a plugin command?

**Comment by magal1337** [comment]
yeap for goRef function can you open another issue with more details?  So I can take a look.  Regarding the compile issue that you have thats interesting and could be a bug. How did you open this file first time? It was directly or by for example a file tree plugin?

**Comment by ashish10alex** [comment]
Sure, interesting again. 
1. The error I had got was when I opened neovim and navigated to the file using Telescope and ran `DataformCompileFull`
2. If I go to the directory itself. Lets say `definitions/outputs/test.sqlx` then it successfully runs `DataformCompileFull`. But that wouldn't be the smoothest of experience imo

**Comment by magal1337** [comment]
@ashish10alex yeap you are correct in theory it should automatically compile project when open a `.sqlx` file first time but its not happening when you try to open it by telescope or file tree plugin. Let me create a branch to work on that and let you know once done.

**Comment by magal1337** [comment]
Hey @ashish10alex  please try to refresh the plugin and test it please if the bug still persist let me know so I can reopen this issue...

**Comment by ashish10alex** [comment]
thanks @magal1337 , I can confirm that your MR fixes the issue
